### ISSUE TITLE
Definir APP

### ISSUE THREAD

**Issue by ivanmoret** [ivanmoret/eq5#1]
Definir que hará vuestra aplicación.

Teneis que acordar que aplicacion web quereis hacer. Si no teneis ni idea podeis hacer la aplicacion para registrar a los alumnos que van al baño.
Podeis ir comentando por aquí lo que pensais hacer.

**Comment by JosueweSalvatge** [comment]
hola companys, de que voleu fer s'aplicació?

**Comment by rafelbarcelo** [comment]
Hola, podem fer loq volgueu fer

**Comment by soberania** [comment]
De lo que vos faci més ràbia! jajajaj

**Comment by Mmperez14** [comment]
hola, teniu qualque idea?

**Comment by soberania** [comment]
nouuuuuuuupppppppppp

**Comment by JosueweSalvatge** [comment]
posam això i ja?

**Comment by rafelbarcelo** [comment]
Sí

**Comment by ivanmoret** [comment]
Que alguien cierre la incidencia!
