### ISSUE TITLE
Redacta el README

### ISSUE THREAD

**Issue by ivanmoret** [ivanmoret/eq5#2]
Haced una explicación de vuestra aplicación web y copiadla al readme en la página principal del repositorio.
Podéis usar comentarios o crearos un documento compartido para hacer trabajar sobre el texto antes de publicarlo.

**Comment by JosueweSalvatge** [comment]
vale!
+

**Comment by ivanmoret** [comment]
Perfecte!!
Pots tancar la incidencia!!
