### ISSUE TITLE
Crear la aplicación

### ISSUE THREAD

**Issue by ivanmoret** [ivanmoret/eq5#4]
Crea la aplicación. Puedes consultar el tutorial de [djangogirls](https://tutorial.djangogirls.org/es/django_models/), pero RECUERDA, en lugar de "blog" debes poner el nombre de tu aplicación.

Una vez hecho haz un commit, un push y pide a tus compañeros que hagan un pull.

**Comment by JosueweSalvatge** [comment]
yaestá!!!!!!!!

**Comment by ivanmoret** [comment]
@JosueweSalvatge Pero a ti quien te ha dado vela en este entierro?
Esto estaba asignado a @soberania y @Mmperez14 .
